// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto

public interface SegmentProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SegmentProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 x = 1;</code>
   * @return Whether the x field is set.
   */
  boolean hasX();
  /**
   * <code>required int32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>required int32 y = 2;</code>
   * @return Whether the y field is set.
   */
  boolean hasY();
  /**
   * <code>required int32 y = 2;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>required bool isHead = 3;</code>
   * @return Whether the isHead field is set.
   */
  boolean hasIsHead();
  /**
   * <code>required bool isHead = 3;</code>
   * @return The isHead.
   */
  boolean getIsHead();
}
