// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto

/**
 * Protobuf type {@code SnakesProto}
 */
public final class SnakesProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SnakesProto)
    SnakesProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SnakesProto.newBuilder() to construct.
  private SnakesProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SnakesProto() {
    units_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SnakesProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SnakesProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            x_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            y_ = input.readInt32();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              units_ = new java.util.ArrayList<UnitProto>();
              mutable_bitField0_ |= 0x00000004;
            }
            units_.add(
                input.readMessage(UnitProto.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        units_ = java.util.Collections.unmodifiableList(units_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Snakes.internal_static_SnakesProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Snakes.internal_static_SnakesProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SnakesProto.class, SnakesProto.Builder.class);
  }

  private int bitField0_;
  public static final int X_FIELD_NUMBER = 1;
  private int x_;
  /**
   * <code>required int32 x = 1;</code>
   * @return Whether the x field is set.
   */
  @java.lang.Override
  public boolean hasX() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 x = 1;</code>
   * @return The x.
   */
  @java.lang.Override
  public int getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 2;
  private int y_;
  /**
   * <code>required int32 y = 2;</code>
   * @return Whether the y field is set.
   */
  @java.lang.Override
  public boolean hasY() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required int32 y = 2;</code>
   * @return The y.
   */
  @java.lang.Override
  public int getY() {
    return y_;
  }

  public static final int UNITS_FIELD_NUMBER = 4;
  private java.util.List<UnitProto> units_;
  /**
   * <code>repeated .UnitProto units = 4;</code>
   */
  @java.lang.Override
  public java.util.List<UnitProto> getUnitsList() {
    return units_;
  }
  /**
   * <code>repeated .UnitProto units = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends UnitProtoOrBuilder> 
      getUnitsOrBuilderList() {
    return units_;
  }
  /**
   * <code>repeated .UnitProto units = 4;</code>
   */
  @java.lang.Override
  public int getUnitsCount() {
    return units_.size();
  }
  /**
   * <code>repeated .UnitProto units = 4;</code>
   */
  @java.lang.Override
  public UnitProto getUnits(int index) {
    return units_.get(index);
  }
  /**
   * <code>repeated .UnitProto units = 4;</code>
   */
  @java.lang.Override
  public UnitProtoOrBuilder getUnitsOrBuilder(
      int index) {
    return units_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasX()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasY()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getUnitsCount(); i++) {
      if (!getUnits(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, x_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, y_);
    }
    for (int i = 0; i < units_.size(); i++) {
      output.writeMessage(4, units_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, x_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, y_);
    }
    for (int i = 0; i < units_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, units_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SnakesProto)) {
      return super.equals(obj);
    }
    SnakesProto other = (SnakesProto) obj;

    if (hasX() != other.hasX()) return false;
    if (hasX()) {
      if (getX()
          != other.getX()) return false;
    }
    if (hasY() != other.hasY()) return false;
    if (hasY()) {
      if (getY()
          != other.getY()) return false;
    }
    if (!getUnitsList()
        .equals(other.getUnitsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasX()) {
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
    }
    if (hasY()) {
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
    }
    if (getUnitsCount() > 0) {
      hash = (37 * hash) + UNITS_FIELD_NUMBER;
      hash = (53 * hash) + getUnitsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SnakesProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SnakesProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SnakesProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SnakesProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SnakesProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SnakesProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SnakesProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SnakesProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SnakesProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SnakesProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SnakesProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SnakesProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SnakesProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SnakesProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SnakesProto)
      SnakesProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Snakes.internal_static_SnakesProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Snakes.internal_static_SnakesProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SnakesProto.class, SnakesProto.Builder.class);
    }

    // Construct using SnakesProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUnitsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      x_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      y_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (unitsBuilder_ == null) {
        units_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        unitsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Snakes.internal_static_SnakesProto_descriptor;
    }

    @java.lang.Override
    public SnakesProto getDefaultInstanceForType() {
      return SnakesProto.getDefaultInstance();
    }

    @java.lang.Override
    public SnakesProto build() {
      SnakesProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public SnakesProto buildPartial() {
      SnakesProto result = new SnakesProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.x_ = x_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.y_ = y_;
        to_bitField0_ |= 0x00000002;
      }
      if (unitsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          units_ = java.util.Collections.unmodifiableList(units_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.units_ = units_;
      } else {
        result.units_ = unitsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SnakesProto) {
        return mergeFrom((SnakesProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SnakesProto other) {
      if (other == SnakesProto.getDefaultInstance()) return this;
      if (other.hasX()) {
        setX(other.getX());
      }
      if (other.hasY()) {
        setY(other.getY());
      }
      if (unitsBuilder_ == null) {
        if (!other.units_.isEmpty()) {
          if (units_.isEmpty()) {
            units_ = other.units_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureUnitsIsMutable();
            units_.addAll(other.units_);
          }
          onChanged();
        }
      } else {
        if (!other.units_.isEmpty()) {
          if (unitsBuilder_.isEmpty()) {
            unitsBuilder_.dispose();
            unitsBuilder_ = null;
            units_ = other.units_;
            bitField0_ = (bitField0_ & ~0x00000004);
            unitsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUnitsFieldBuilder() : null;
          } else {
            unitsBuilder_.addAllMessages(other.units_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasX()) {
        return false;
      }
      if (!hasY()) {
        return false;
      }
      for (int i = 0; i < getUnitsCount(); i++) {
        if (!getUnits(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SnakesProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SnakesProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int x_ ;
    /**
     * <code>required int32 x = 1;</code>
     * @return Whether the x field is set.
     */
    @java.lang.Override
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }
    /**
     * <code>required int32 x = 1;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(int value) {
      bitField0_ |= 0x00000001;
      x_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 x = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000001);
      x_ = 0;
      onChanged();
      return this;
    }

    private int y_ ;
    /**
     * <code>required int32 y = 2;</code>
     * @return Whether the y field is set.
     */
    @java.lang.Override
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }
    /**
     * <code>required int32 y = 2;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(int value) {
      bitField0_ |= 0x00000002;
      y_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 y = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      bitField0_ = (bitField0_ & ~0x00000002);
      y_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<UnitProto> units_ =
      java.util.Collections.emptyList();
    private void ensureUnitsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        units_ = new java.util.ArrayList<UnitProto>(units_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        UnitProto, UnitProto.Builder, UnitProtoOrBuilder> unitsBuilder_;

    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public java.util.List<UnitProto> getUnitsList() {
      if (unitsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(units_);
      } else {
        return unitsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public int getUnitsCount() {
      if (unitsBuilder_ == null) {
        return units_.size();
      } else {
        return unitsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public UnitProto getUnits(int index) {
      if (unitsBuilder_ == null) {
        return units_.get(index);
      } else {
        return unitsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public Builder setUnits(
        int index, UnitProto value) {
      if (unitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnitsIsMutable();
        units_.set(index, value);
        onChanged();
      } else {
        unitsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public Builder setUnits(
        int index, UnitProto.Builder builderForValue) {
      if (unitsBuilder_ == null) {
        ensureUnitsIsMutable();
        units_.set(index, builderForValue.build());
        onChanged();
      } else {
        unitsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public Builder addUnits(UnitProto value) {
      if (unitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnitsIsMutable();
        units_.add(value);
        onChanged();
      } else {
        unitsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public Builder addUnits(
        int index, UnitProto value) {
      if (unitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnitsIsMutable();
        units_.add(index, value);
        onChanged();
      } else {
        unitsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public Builder addUnits(
        UnitProto.Builder builderForValue) {
      if (unitsBuilder_ == null) {
        ensureUnitsIsMutable();
        units_.add(builderForValue.build());
        onChanged();
      } else {
        unitsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public Builder addUnits(
        int index, UnitProto.Builder builderForValue) {
      if (unitsBuilder_ == null) {
        ensureUnitsIsMutable();
        units_.add(index, builderForValue.build());
        onChanged();
      } else {
        unitsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public Builder addAllUnits(
        java.lang.Iterable<? extends UnitProto> values) {
      if (unitsBuilder_ == null) {
        ensureUnitsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, units_);
        onChanged();
      } else {
        unitsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public Builder clearUnits() {
      if (unitsBuilder_ == null) {
        units_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        unitsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public Builder removeUnits(int index) {
      if (unitsBuilder_ == null) {
        ensureUnitsIsMutable();
        units_.remove(index);
        onChanged();
      } else {
        unitsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public UnitProto.Builder getUnitsBuilder(
        int index) {
      return getUnitsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public UnitProtoOrBuilder getUnitsOrBuilder(
        int index) {
      if (unitsBuilder_ == null) {
        return units_.get(index);  } else {
        return unitsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public java.util.List<? extends UnitProtoOrBuilder> 
         getUnitsOrBuilderList() {
      if (unitsBuilder_ != null) {
        return unitsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(units_);
      }
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public UnitProto.Builder addUnitsBuilder() {
      return getUnitsFieldBuilder().addBuilder(
          UnitProto.getDefaultInstance());
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public UnitProto.Builder addUnitsBuilder(
        int index) {
      return getUnitsFieldBuilder().addBuilder(
          index, UnitProto.getDefaultInstance());
    }
    /**
     * <code>repeated .UnitProto units = 4;</code>
     */
    public java.util.List<UnitProto.Builder> 
         getUnitsBuilderList() {
      return getUnitsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        UnitProto, UnitProto.Builder, UnitProtoOrBuilder> 
        getUnitsFieldBuilder() {
      if (unitsBuilder_ == null) {
        unitsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            UnitProto, UnitProto.Builder, UnitProtoOrBuilder>(
                units_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        units_ = null;
      }
      return unitsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SnakesProto)
  }

  // @@protoc_insertion_point(class_scope:SnakesProto)
  private static final SnakesProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SnakesProto();
  }

  public static SnakesProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SnakesProto>
      PARSER = new com.google.protobuf.AbstractParser<SnakesProto>() {
    @java.lang.Override
    public SnakesProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SnakesProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SnakesProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SnakesProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public SnakesProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

