// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto

public interface SnakesProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SnakesProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 x = 1;</code>
   * @return Whether the x field is set.
   */
  boolean hasX();
  /**
   * <code>required int32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>required int32 y = 2;</code>
   * @return Whether the y field is set.
   */
  boolean hasY();
  /**
   * <code>required int32 y = 2;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>repeated .UnitProto units = 4;</code>
   */
  java.util.List<UnitProto> 
      getUnitsList();
  /**
   * <code>repeated .UnitProto units = 4;</code>
   */
  UnitProto getUnits(int index);
  /**
   * <code>repeated .UnitProto units = 4;</code>
   */
  int getUnitsCount();
  /**
   * <code>repeated .UnitProto units = 4;</code>
   */
  java.util.List<? extends UnitProtoOrBuilder> 
      getUnitsOrBuilderList();
  /**
   * <code>repeated .UnitProto units = 4;</code>
   */
  UnitProtoOrBuilder getUnitsOrBuilder(
      int index);
}
