// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto

public final class Snakes {
  private Snakes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SnakesProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SnakesProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnitProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UnitProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SegmentProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SegmentProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014snakes.proto\">\n\013SnakesProto\022\t\n\001x\030\001 \002(\005" +
      "\022\t\n\001y\030\002 \002(\005\022\031\n\005units\030\004 \003(\0132\n.UnitProto\"\247" +
      "\001\n\tUnitProto\022\014\n\004code\030\001 \002(\005\022\016\n\006points\030\002 \001" +
      "(\005\022\037\n\010segments\030\003 \003(\0132\r.SegmentProto\022\'\n\td" +
      "irection\030\004 \001(\0162\024.UnitProto.Direction\"2\n\t" +
      "Direction\022\006\n\002UP\020\000\022\010\n\004DOWN\020\001\022\010\n\004LEFT\020\002\022\t\n" +
      "\005RIGHT\020\003\"4\n\014SegmentProto\022\t\n\001x\030\001 \002(\005\022\t\n\001y" +
      "\030\002 \002(\005\022\016\n\006isHead\030\003 \002(\010B\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SnakesProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SnakesProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SnakesProto_descriptor,
        new java.lang.String[] { "X", "Y", "Units", });
    internal_static_UnitProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UnitProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UnitProto_descriptor,
        new java.lang.String[] { "Code", "Points", "Segments", "Direction", });
    internal_static_SegmentProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SegmentProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SegmentProto_descriptor,
        new java.lang.String[] { "X", "Y", "IsHead", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
