// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snakes.proto

public interface UnitProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnitProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 code = 1;</code>
   * @return Whether the code field is set.
   */
  boolean hasCode();
  /**
   * <code>required int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>optional int32 points = 2;</code>
   * @return Whether the points field is set.
   */
  boolean hasPoints();
  /**
   * <code>optional int32 points = 2;</code>
   * @return The points.
   */
  int getPoints();

  /**
   * <code>repeated .SegmentProto segments = 3;</code>
   */
  java.util.List<SegmentProto> 
      getSegmentsList();
  /**
   * <code>repeated .SegmentProto segments = 3;</code>
   */
  SegmentProto getSegments(int index);
  /**
   * <code>repeated .SegmentProto segments = 3;</code>
   */
  int getSegmentsCount();
  /**
   * <code>repeated .SegmentProto segments = 3;</code>
   */
  java.util.List<? extends SegmentProtoOrBuilder> 
      getSegmentsOrBuilderList();
  /**
   * <code>repeated .SegmentProto segments = 3;</code>
   */
  SegmentProtoOrBuilder getSegmentsOrBuilder(
      int index);

  /**
   * <code>optional .UnitProto.Direction direction = 4;</code>
   * @return Whether the direction field is set.
   */
  boolean hasDirection();
  /**
   * <code>optional .UnitProto.Direction direction = 4;</code>
   * @return The direction.
   */
  UnitProto.Direction getDirection();
}
